# Generated by Django 2.2.2 on 2019-06-10 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 16, 3, 58, 439486, tzinfo=utc)),
        ),
    ]
