# Generated by Django 2.2.2 on 2019-06-10 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190610_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
